#!/bin/bash

echo "Installing Spotify.."

tmpdir=$(mktemp -d)
cd $tmpdir

curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | apt-key add -
echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list

apt update
apt install -y spotify-client

echo ""
echo "Installation complete"
echo ""
